<?php $meta=['title'=>'About Ezzo.sg | Premium Doors, Windows & Skylights Singapore','description'=>'Ezzo.sg supplies and installs premium aluminium doors, windows and skylights in Singapore, with custom sizing, glass options, project coordination and after-sales support.']; include __DIR__.'/includes/header.php'; ?>
<section class="page-hero"><div class="container"><div class="eyebrow">About the company</div><h1>Designed for light, built for living.</h1><p>Ezzo.sg is a Singapore-focused brand for premium aluminium doors, windows and skylight systems.</p><div class="hero-actions"><a class="btn btn-accent" href="/quote">Get a Free Quote</a></div></div></section>

<section class="section"><div class="container split"><div><div class="eyebrow">Our promise</div><h2>Complete product solutions, not just supply.</h2><p>We help homeowners, landed-property owners, designers, architects, contractors and commercial clients select suitable systems for openings, facades, roofs and interior spaces where design, performance and installation quality matter. Our work is not only about supplying a product. A good door, window or skylight depends on the right frame profile, glass configuration, opening method, hardware, site measurement, waterproofing detail, installation approach and after-sales support. Ezzo.sg brings these parts together so clients can make clearer decisions before fabrication and installation.</p><ul class="tick-list"><li>Premium aluminium profiles and glass options</li><li>Custom measured systems for each project</li><li>Quality inspection before delivery</li><li>Installation guidance and after-sales support</li></ul></div><img src="<?=e(asset('images/About ezzo.sg.webp'))?>" alt="About EZZO.SG company"></div></section>

<section class="section category-band"><div class="container"><div class="grid-3"><div class="info-card card-body"><span class="pill">Mission</span><h3>Better spaces</h3><p>To help Singapore homeowners and businesses create brighter, more durable and more refined spaces.</p></div><div class="info-card card-body"><span class="pill">Approach</span><h3>Technical clarity</h3><p>We guide model choice, glass specification, finish selection, opening method and installation details before production.</p></div><div class="info-card card-body"><span class="pill">Support</span><h3>After-sales care</h3><p>Customers receive practical support after installation for smoother long-term ownership.</p></div></div></div></section>
<section class="cta"><div class="container"><h2>Need product advice?</h2><p>If you are planning to upgrade doors, windows or skylights, contact Ezzo.sg with your property type, opening size, preferred design and project timeline. Our team can help review the requirement and recommend a suitable next step.</p><a class="btn btn-accent" href="/quote">Get a Free Quote</a></div></section>
<section class="section category-band"><div class="container"><div class="grid-2"><div class="info-card card-body"><h3 class="pill">What We Provide</h3>
<p>Ezzo.sg focuses on modern aluminium and glass systems for Singapore homes and commercial properties. Our product range includes sliding doors, folding doors, casement windows, sliding windows, skylights, sunroofs, entrance-door references and selected custom aluminium-glass solutions. Depending on the project requirement, we can advise on profile type, glass selection, colour and finish, opening direction, ventilation, daylight, weather exposure, acoustic comfort and maintenance considerations. Some projects require clean visual design. Others require stronger weather sealing, larger openings, sound reduction or easier long-term use. The final recommendation should always follow the site condition and customer objective.</p></div><div class="info-card card-body"><h3 class="pill">Backed by Ezzogenics</h3><p>Ezzo.sg is supported by Ezzogenics Pte Ltd, a Singapore contractor with experience across renovation, glass works, metal works, waterproofing, flooring, facade-related works, work-at-height support and building maintenance. This broader contractor background helps us look beyond the product alone and consider how the system will perform within the actual building. Ezzogenics Pte Ltd has attained bizSAFE Level 3, holds a BCA GB2 Builder Licence, and is registered under BCA CR06 Interior Decoration & Finishing Works. The company is also listed under the HDB Directory of Registered Contractors. These credentials support a practical, site-aware approach to project coordination, installation planning and customer support.</p></div><div class="info-card card-body"><h3 class="pill">How We Work</h3><p>Our process starts with understanding the project. We review the opening type, usage, building condition, design preference, budget direction and installation constraints. Where needed, we arrange a site visit or request measurements, photos and drawings so the recommendation can be more accurate. After product selection, we prepare the quotation and coordinate the next steps for confirmation, production, delivery and installation. We aim to keep communication clear so customers understand what is being supplied, what needs to be confirmed, and what may depend on site conditions.
</p></div><div class="info-card card-body"><h3 class="pill">Why Choose Ezzo.sg</h3><p>Our systems can support better natural light, improved ventilation, stronger visual connection between spaces, and more comfortable living or working environments. Every project is different. A landed home may need larger sliding or folding openings. A condominium unit may need a cleaner window upgrade. A commercial space may need aluminium-glass systems that look professional and are practical to maintain. A skylight project may need careful attention to waterproofing, access, drainage and glass selection. Ezzo.sg provides a clearer starting point for these discussions, with product knowledge, contractor awareness and installation support under one coordinated brand.</p></div></div></div></section>

<section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Service flow</div><h2>A clear process from inquiry to acceptance.</h2></div></div><div class="grid-4"><?php foreach(['Customer inquiry','Requirement review','Site visit and quotation','Contract and deposit','Production scheduling','Quality inspection','Delivery and installation','After-sales service'] as $i=>$step): ?><div class="feature-card"><div class="feature-icon"><?=($i+1)?></div><h3><?=e($step)?></h3></div><?php endforeach; ?></div></div></section>




<?php include __DIR__.'/includes/footer.php'; ?>
