<?php
require_once __DIR__.'/includes/functions.php';
$slug=$_GET['slug']??'';
$project=get_project_by_slug($slug);
if(!$project){http_response_code(404);$meta=['title'=>'Project Not Found | ezzo.sg'];include __DIR__.'/includes/header.php';echo '<section class="page-hero"><div class="container"><h1>Project not found</h1><p>The project may have been moved or unpublished.</p><a class="btn btn-light" href="/projects">Back to projects</a></div></section>';include __DIR__.'/includes/footer.php';exit;}
$gallery=array_values(array_unique(array_filter(array_merge([$project['main_image']], split_lines($project['gallery_images'] ?? '')))));
$gallery=array_map('media_src',$gallery);
$meta=['title'=>($project['seo_title'] ?? $project['title'].' | Project Detail | ezzo.sg'),'description'=>$project['description'],'image'=>url($project['main_image']),'type'=>'article'];
$schema_markup=['@context'=>'https://schema.org','@type'=>'CreativeWork','name'=>$project['title'],'description'=>$project['description'],'image'=>array_map(fn($g)=>url($g),$gallery),'locationCreated'=>$project['location'],'url'=>url('project/'.$project['slug'])];
include __DIR__.'/includes/header.php';
$related=get_related_projects($project,3);
?>
<section class="page-hero" style="background-image:linear-gradient(237deg, #12384a52, #2938472e),url('<?=e(media_src($project['main_image']))?>')"><div class="container"><div class="eyebrow"><?=e($project['project_type'])?> project</div><h1><?=e($project['title'])?></h1><p><?=e($project['description'])?></p><div class="hero-actions"><a class="btn btn-accent" href="/quote">Request Similar Project Quote</a><a class="btn btn-light" href="/projects">Back to Projects</a></div></div></section>
<section class="section"><div class="container"><div class="project-meta"><div><span>Location</span><strong><?=e($project['location'])?></strong></div><div><span>Year</span><strong><?=e($project['year'] ?? '2026')?></strong></div><div><span>Type</span><strong><?=e($project['project_type'])?></strong></div><div><span>Products</span><strong><?=e($project['product_type'])?></strong></div></div><div class="gallery-grid"><?php foreach($gallery as $g): ?><img loading="lazy" data-lightbox="<?=e($g)?>" src="<?=e($g)?>" alt="<?=e($project['title'])?> gallery image"><?php endforeach; ?></div></div></section>
<section class="section2"><div><div class="eyebrow">Project detail</div><h2>Scope, challenges and solution.</h2><div><div><img style="border-radius:var(--radius);box-shadow:var(--shadow);height:800px;object-fit:cover;width:100%" src="<?=e(media_src($project['main_image']))?>" alt="<?=e($project['title'])?> hero"></div></div><div class="container split"style="gap:20px; align-items:stretch;margin-top:30px;"><div class="detail-block"><h3>Project description</h3><p><?=e($project['description'])?></p></div><div class="detail-block"><h3>Scope</h3><p><?=e($project['scope'] ?? $project['product_type'])?></p></div><div class="detail-block"><h3>Challenges</h3><p><?=e($project['challenges'] ?? 'Site-specific design, measurement and installation requirements were reviewed before production.')?></p></div><div class="detail-block"><h3>Solutions</h3><p><?=e($project['solutions'] ?? 'The solution was specified with suitable aluminium profiles, glass, hardware and installation detailing.')?></p></div></div></div></section>

<?php if($related): ?><section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Related projects</div><h2>More installation examples.</h2></div></div><div class="grid-3"><?php foreach($related as $p): ?><article class="project-card"><img loading="lazy" src="<?=e(media_src($p['main_image']))?>" alt="<?=e($p['title'])?>"><div class="card-body"><span class="pill"><?=e($p['project_type'])?></span><h3><?=e($p['title'])?></h3><p><?=e($p['description'])?></p><a class="card-link" href="<?=e(project_link($p['slug']))?>">View project</a></div></article><?php endforeach; ?></div></div></section><?php endif; ?>
<?php include __DIR__.'/includes/footer.php'; ?>
