<?php
$admin_title='Product Editor'; include __DIR__.'/inc/header.php'; $pdo=db(); $id=(int)($_GET['id']??0); $product=$id?fetch_one("SELECT * FROM products WHERE id=?",[$id]):null; $cats=get_categories();
$cols=db_table_columns('products');
function keep_cols(array $data,array $cols): array { return array_intersect_key($data, array_flip($cols)); }
if($pdo && $_SERVER['REQUEST_METHOD']==='POST'){
  $id=(int)($_POST['id']??0); $name=trim($_POST['name']??''); $slug=slugify($_POST['slug'] ?: $name);
  $image=upload_image('hero_image','products') ?: ($_POST['current_image'] ?? '');
  $data=[
    'category_id'=>($_POST['category_id']?:null),'name'=>$name,'slug'=>$slug,'subcategory'=>trim($_POST['subcategory']??''),'model_code'=>trim($_POST['model_code']??''),'short_description'=>trim($_POST['short_description']??''),'description'=>trim($_POST['description']??''),'features'=>trim($_POST['features']??''),'specifications'=>trim($_POST['specifications']??''),'materials'=>trim($_POST['materials']??''),'colors'=>trim($_POST['colors']??''),'benefits'=>trim($_POST['benefits']??''),'finishes_options'=>trim($_POST['finishes_options']??''),'technical_data'=>trim($_POST['technical_data']??''),'seo_title'=>trim($_POST['seo_title']??''),'meta_description'=>trim($_POST['meta_description']??''),'gallery_images'=>trim($_POST['gallery_images']??''),'hero_image'=>$image,'featured'=>(int)isset($_POST['featured']),'sort_order'=>(int)($_POST['sort_order']??0),'status'=>$_POST['status']??'published'
  ];
  $data=keep_cols($data,$cols);
  if($id){$sets=implode(',',array_map(fn($k)=>"`$k`=?",array_keys($data)));$pdo->prepare("UPDATE products SET $sets WHERE id=?")->execute([...array_values($data),$id]);}
  else{$keys=array_keys($data);$ph=implode(',',array_fill(0,count($keys),'?'));$created=in_array('created_at',$cols,true)?',created_at':'';$createdVal=in_array('created_at',$cols,true)?',NOW()':'';$pdo->prepare("INSERT INTO products(`".implode('`,`',$keys)."`$created) VALUES($ph$createdVal)")->execute(array_values($data));}
  header('Location: products.php'); exit;
}
$p=$product ?: ['id'=>'','category_id'=>'','name'=>'','slug'=>'','subcategory'=>'','model_code'=>'','short_description'=>'','description'=>'','features'=>'','specifications'=>'','materials'=>'','colors'=>'','benefits'=>'','finishes_options'=>'','technical_data'=>'','seo_title'=>'','meta_description'=>'','gallery_images'=>'','hero_image'=>'','featured'=>0,'sort_order'=>0,'status'=>'published'];
?>
<div class="admin-help">Use one item per line or separate values with <code>|</code> for features, specifications, finishes, benefits and gallery images. Import the v2 schema to store model code, subcategory, SEO and technical data as dedicated fields.</div>
<div class="admin-card"><form method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="<?= e($p['id']) ?>"><input type="hidden" name="current_image" value="<?= e($p['hero_image']) ?>"><div class="form-grid"><select name="category_id"><option value="">Category</option><?php foreach($cats as $c): ?><option value="<?= e($c['id']) ?>" <?= ($p['category_id']==$c['id'])?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select><input name="name" required placeholder="Product name" value="<?= e($p['name']) ?>"><input name="slug" placeholder="slug" value="<?= e($p['slug']) ?>"><input name="model_code" placeholder="Model code, e.g. PRO110" value="<?= e($p['model_code'] ?? '') ?>"><input name="subcategory" placeholder="Product family, e.g. Casement Window" value="<?= e($p['subcategory'] ?? '') ?>"><input name="sort_order" type="number" value="<?= e($p['sort_order']) ?>"><textarea class="full" name="short_description" placeholder="Short SEO-friendly card description"><?= e($p['short_description']) ?></textarea><textarea class="full" name="description" placeholder="Detailed product description"><?= e($p['description']) ?></textarea><textarea name="features" placeholder="Features, one per line or separated by |"><?= e($p['features']) ?></textarea><textarea name="specifications" placeholder="Specifications table rows, e.g. Frame width: 110 mm"><?= e($p['specifications']) ?></textarea><textarea name="materials" placeholder="Materials"><?= e($p['materials']) ?></textarea><textarea name="colors" placeholder="Available colors / finishes"><?= e($p['colors']) ?></textarea><textarea class="full" name="finishes_options" placeholder="Finishes and options"><?= e($p['finishes_options'] ?? '') ?></textarea><textarea class="full" name="technical_data" placeholder="Technical data notes"><?= e($p['technical_data'] ?? '') ?></textarea><textarea class="full" name="benefits" placeholder="Benefits"><?= e($p['benefits']) ?></textarea><textarea class="full" name="gallery_images" placeholder="Gallery image URLs/paths, one per line"><?= e($p['gallery_images']) ?></textarea><input class="full" name="seo_title" placeholder="SEO title" value="<?= e($p['seo_title'] ?? '') ?>"><textarea class="full" name="meta_description" placeholder="Meta description"><?= e($p['meta_description'] ?? '') ?></textarea><input type="file" name="hero_image" accept="image/*"><select name="status"><option value="published">Published</option><option value="draft" <?= $p['status']==='draft'?'selected':'' ?>>Draft</option></select><label class="radio-card"><input type="checkbox" name="featured" <?= $p['featured']?'checked':'' ?>> Featured product</label><button class="btn btn-accent full">Save Product</button></div></form></div>
<?php include __DIR__.'/inc/footer.php'; ?>
