<?php
$admin_title='Projects'; include __DIR__.'/inc/header.php'; $pdo=db(); $cols=db_table_columns('projects');
function project_keep_cols(array $data,array $cols): array { return array_intersect_key($data, array_flip($cols)); }
if($pdo && isset($_POST['delete'])){$pdo->prepare("DELETE FROM projects WHERE id=?")->execute([(int)$_POST['delete']]);}
if($pdo && $_SERVER['REQUEST_METHOD']==='POST' && !isset($_POST['delete'])){
  $id=(int)($_POST['id']??0); $title=trim($_POST['title']??''); $slug=slugify($_POST['slug'] ?: $title); $image=upload_image('main_image','projects') ?: ($_POST['current_image'] ?? '');
  $data=['title'=>$title,'slug'=>$slug,'location'=>trim($_POST['location']??''),'project_type'=>trim($_POST['project_type']??''),'filters'=>trim($_POST['filters']??''),'product_type'=>trim($_POST['product_type']??''),'description'=>trim($_POST['description']??''),'scope'=>trim($_POST['scope']??''),'challenges'=>trim($_POST['challenges']??''),'solutions'=>trim($_POST['solutions']??''),'materials_used'=>trim($_POST['materials_used']??''),'project_year'=>trim($_POST['project_year']??''),'gallery_images'=>trim($_POST['gallery_images']??''),'before_images'=>trim($_POST['before_images']??''),'after_images'=>trim($_POST['after_images']??''),'main_image'=>$image,'seo_title'=>trim($_POST['seo_title']??''),'meta_description'=>trim($_POST['meta_description']??''),'featured'=>(int)isset($_POST['featured']),'status'=>$_POST['status']??'published'];
  $data=project_keep_cols($data,$cols);
  if($id){$sets=implode(',',array_map(fn($k)=>"`$k`=?",array_keys($data)));$pdo->prepare("UPDATE projects SET $sets WHERE id=?")->execute([...array_values($data),$id]);}
  else{$keys=array_keys($data);$ph=implode(',',array_fill(0,count($keys),'?'));$created=in_array('created_at',$cols,true)?',created_at':'';$createdVal=in_array('created_at',$cols,true)?',NOW()':'';$pdo->prepare("INSERT INTO projects(`".implode('`,`',$keys)."`$created) VALUES($ph$createdVal)")->execute(array_values($data));}
  header('Location: projects.php'); exit;
}
$edit=isset($_GET['id'])?fetch_one("SELECT * FROM projects WHERE id=?",[(int)$_GET['id']]):null; $rows=fetch_all("SELECT * FROM projects ORDER BY id DESC");
$p=$edit ?: ['id'=>'','title'=>'','slug'=>'','location'=>'','project_type'=>'Residential','filters'=>'','product_type'=>'','description'=>'','scope'=>'','challenges'=>'','solutions'=>'','materials_used'=>'','project_year'=>'','gallery_images'=>'','before_images'=>'','after_images'=>'','main_image'=>'','seo_title'=>'','meta_description'=>'','featured'=>0,'status'=>'published'];
?>
<div class="admin-card"><h2><?= $edit?'Edit':'Add' ?> Project</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="<?= e($p['id']) ?>"><input type="hidden" name="current_image" value="<?= e($p['main_image']) ?>"><div class="form-grid"><input name="title" required placeholder="Project title" value="<?= e($p['title']) ?>"><input name="slug" placeholder="slug" value="<?= e($p['slug']) ?>"><input name="location" placeholder="Location" value="<?= e($p['location']) ?>"><input name="project_year" placeholder="Year" value="<?= e($p['project_year'] ?? $p['year'] ?? '') ?>"><select name="project_type"><option>Residential</option><option <?= $p['project_type']==='Commercial'?'selected':'' ?>>Commercial</option><option <?= $p['project_type']==='Doors'?'selected':'' ?>>Doors</option><option <?= $p['project_type']==='Windows'?'selected':'' ?>>Windows</option><option <?= $p['project_type']==='Skylights'?'selected':'' ?>>Skylights</option></select><input name="filters" placeholder="Filter tags e.g. residential doors windows" value="<?= e($p['filters'] ?? '') ?>"><input class="full" name="product_type" placeholder="Products used" value="<?= e($p['product_type']) ?>"><textarea class="full" name="description" placeholder="Project description"><?= e($p['description']) ?></textarea><textarea class="full" name="scope" placeholder="Scope"><?= e($p['scope'] ?? '') ?></textarea><textarea name="challenges" placeholder="Challenges"><?= e($p['challenges'] ?? '') ?></textarea><textarea name="solutions" placeholder="Solutions"><?= e($p['solutions'] ?? '') ?></textarea><textarea class="full" name="materials_used" placeholder="Materials used"><?= e($p['materials_used'] ?? '') ?></textarea><textarea name="gallery_images" placeholder="Gallery image paths/URLs, one per line"><?= e($p['gallery_images'] ?? '') ?></textarea><textarea name="before_images" placeholder="Before images, one per line"><?= e($p['before_images']) ?></textarea><textarea name="after_images" placeholder="After images, one per line"><?= e($p['after_images']) ?></textarea><input type="file" name="main_image" accept="image/*"><select name="status"><option>published</option><option <?= $p['status']==='draft'?'selected':'' ?>>draft</option></select><input class="full" name="seo_title" placeholder="SEO title" value="<?= e($p['seo_title'] ?? '') ?>"><textarea class="full" name="meta_description" placeholder="Meta description"><?= e($p['meta_description'] ?? '') ?></textarea><label class="radio-card"><input type="checkbox" name="featured" <?= $p['featured']?'checked':'' ?>> Featured project</label><button class="btn btn-accent full">Save Project</button></div></form></div>
<table class="table"><tr><th>Image</th><th>Project</th><th>Type</th><th>Location</th><th>Actions</th></tr><?php foreach($rows as $r): ?><tr><td><img src="../<?= e($r['main_image']) ?>" style="width:90px;height:70px;object-fit:cover;border-radius:10px" onerror="this.src='<?= e($r['main_image']) ?>'"></td><td><?= e($r['title']) ?><br><small><?= e($r['slug']) ?></small></td><td><?= e($r['project_type']) ?></td><td><?= e($r['location']) ?></td><td><a class="btn btn-small" href="projects.php?id=<?= e($r['id']) ?>">Edit</a><form method="post" style="display:inline"><button class="btn btn-small" name="delete" value="<?= e($r['id']) ?>" onclick="return confirm('Delete project?')">Delete</button></form></td></tr><?php endforeach; ?></table>
<?php include __DIR__.'/inc/footer.php'; ?>
